#ifndef __SAI_METADATA_H__
#define __SAI_METADATA_H__
/* AUTOGENERATED FILE! DO NOT EDIT! */
#include <sai.h>
#include "saimetadatatypes.h"
#include "saimetadatautils.h"
#include "saimetadatalogger.h"
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_action_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_bind_point_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_counter_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_ip_frag_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_ip_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_range_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_range_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_stage_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_table_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_table_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_table_group_member_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_acl_table_group_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_api_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_attr_condition_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_attr_flags_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_attr_value_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_bridge_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_bridge_port_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_bridge_port_fdb_learning_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_bridge_port_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_bridge_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_buffer_pool_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_buffer_pool_stat_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_buffer_pool_threshold_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_buffer_pool_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_buffer_profile_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_buffer_profile_threshold_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_bulk_op_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_common_api_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_default_value_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_ecn_mark_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_erspan_encapsulation_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_fdb_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_fdb_entry_bridge_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_fdb_entry_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_fdb_event_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_fdb_flush_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_fdb_flush_entry_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hash_algorithm_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hash_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_packet_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_table_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_table_entry_channel_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_table_entry_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_trap_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_trap_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_trap_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_tx_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_user_defined_trap_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_user_defined_trap_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_hostif_vlan_tag_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_ingress_priority_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_ingress_priority_group_stat_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_ip_addr_family_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_ipmc_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_ipmc_entry_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_ipmc_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_ipmc_group_member_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_l2mc_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_l2mc_entry_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_l2mc_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_l2mc_group_member_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_lag_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_lag_member_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_log_level_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_mcast_fdb_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_meter_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_mirror_session_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_mirror_session_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_native_hash_field_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_neighbor_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_next_hop_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_next_hop_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_next_hop_group_member_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_next_hop_group_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_next_hop_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_object_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_packet_action_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_packet_color_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_packet_vlan_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_policer_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_policer_color_source_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_policer_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_policer_stat_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_bind_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_breakout_mode_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_fec_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_flow_control_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_internal_loopback_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_media_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_oper_status_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_stat_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_port_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_qos_map_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_qos_map_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_queue_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_queue_pfc_deadlock_event_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_queue_stat_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_queue_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_route_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_router_interface_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_router_interface_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_rpf_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_rpf_group_member_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_samplepacket_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_samplepacket_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_samplepacket_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_scheduler_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_scheduler_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_scheduling_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_status_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_stp_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_stp_port_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_stp_port_state_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_switch_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_switch_mcast_snooping_capability_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_switch_oper_status_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_switch_restart_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_switch_switching_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_decap_ecn_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_dscp_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_encap_ecn_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_map_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_map_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_map_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_term_table_entry_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_term_table_entry_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_ttl_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_tunnel_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_udf_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_udf_base_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_udf_group_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_udf_group_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_udf_match_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_virtual_router_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_vlan_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_vlan_mcast_lookup_key_type_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_vlan_member_attr_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_vlan_stat_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_vlan_tagging_mode_t;
extern const sai_enum_metadata_t sai_metadata_enum_sai_wred_attr_t;
extern const sai_enum_metadata_t* sai_metadata_all_enums[];
extern const size_t sai_metadata_all_enums_count;
extern const sai_enum_metadata_t* sai_metadata_attr_enums[];
extern const size_t sai_metadata_attr_enums_count;
extern const sai_attr_metadata_t** sai_metadata_attr_by_object_type[];
extern const size_t sai_metadata_attr_by_object_type_count;
extern const char* sai_metadata_get_acl_action_type_name(
        _In_ sai_acl_action_type_t value);
extern const char* sai_metadata_get_acl_bind_point_type_name(
        _In_ sai_acl_bind_point_type_t value);
extern const char* sai_metadata_get_acl_ip_frag_name(
        _In_ sai_acl_ip_frag_t value);
extern const char* sai_metadata_get_acl_ip_type_name(
        _In_ sai_acl_ip_type_t value);
extern const char* sai_metadata_get_acl_range_type_name(
        _In_ sai_acl_range_type_t value);
extern const char* sai_metadata_get_acl_stage_name(
        _In_ sai_acl_stage_t value);
extern const char* sai_metadata_get_acl_table_group_type_name(
        _In_ sai_acl_table_group_type_t value);
extern const char* sai_metadata_get_api_name(
        _In_ sai_api_t value);
extern const char* sai_metadata_get_attr_condition_type_name(
        _In_ sai_attr_condition_type_t value);
extern const char* sai_metadata_get_attr_flags_name(
        _In_ sai_attr_flags_t value);
extern const char* sai_metadata_get_attr_value_type_name(
        _In_ sai_attr_value_type_t value);
extern const char* sai_metadata_get_bridge_port_fdb_learning_mode_name(
        _In_ sai_bridge_port_fdb_learning_mode_t value);
extern const char* sai_metadata_get_bridge_port_type_name(
        _In_ sai_bridge_port_type_t value);
extern const char* sai_metadata_get_bridge_type_name(
        _In_ sai_bridge_type_t value);
extern const char* sai_metadata_get_buffer_pool_stat_name(
        _In_ sai_buffer_pool_stat_t value);
extern const char* sai_metadata_get_buffer_pool_threshold_mode_name(
        _In_ sai_buffer_pool_threshold_mode_t value);
extern const char* sai_metadata_get_buffer_pool_type_name(
        _In_ sai_buffer_pool_type_t value);
extern const char* sai_metadata_get_buffer_profile_threshold_mode_name(
        _In_ sai_buffer_profile_threshold_mode_t value);
extern const char* sai_metadata_get_bulk_op_type_name(
        _In_ sai_bulk_op_type_t value);
extern const char* sai_metadata_get_common_api_name(
        _In_ sai_common_api_t value);
extern const char* sai_metadata_get_default_value_type_name(
        _In_ sai_default_value_type_t value);
extern const char* sai_metadata_get_ecn_mark_mode_name(
        _In_ sai_ecn_mark_mode_t value);
extern const char* sai_metadata_get_erspan_encapsulation_type_name(
        _In_ sai_erspan_encapsulation_type_t value);
extern const char* sai_metadata_get_fdb_entry_bridge_type_name(
        _In_ sai_fdb_entry_bridge_type_t value);
extern const char* sai_metadata_get_fdb_entry_type_name(
        _In_ sai_fdb_entry_type_t value);
extern const char* sai_metadata_get_fdb_event_name(
        _In_ sai_fdb_event_t value);
extern const char* sai_metadata_get_fdb_flush_entry_type_name(
        _In_ sai_fdb_flush_entry_type_t value);
extern const char* sai_metadata_get_hash_algorithm_name(
        _In_ sai_hash_algorithm_t value);
extern const char* sai_metadata_get_hostif_table_entry_channel_type_name(
        _In_ sai_hostif_table_entry_channel_type_t value);
extern const char* sai_metadata_get_hostif_table_entry_type_name(
        _In_ sai_hostif_table_entry_type_t value);
extern const char* sai_metadata_get_hostif_trap_type_name(
        _In_ sai_hostif_trap_type_t value);
extern const char* sai_metadata_get_hostif_tx_type_name(
        _In_ sai_hostif_tx_type_t value);
extern const char* sai_metadata_get_hostif_type_name(
        _In_ sai_hostif_type_t value);
extern const char* sai_metadata_get_hostif_user_defined_trap_type_name(
        _In_ sai_hostif_user_defined_trap_type_t value);
extern const char* sai_metadata_get_hostif_vlan_tag_name(
        _In_ sai_hostif_vlan_tag_t value);
extern const char* sai_metadata_get_ingress_priority_group_stat_name(
        _In_ sai_ingress_priority_group_stat_t value);
extern const char* sai_metadata_get_ip_addr_family_name(
        _In_ sai_ip_addr_family_t value);
extern const char* sai_metadata_get_ipmc_entry_type_name(
        _In_ sai_ipmc_entry_type_t value);
extern const char* sai_metadata_get_l2mc_entry_type_name(
        _In_ sai_l2mc_entry_type_t value);
extern const char* sai_metadata_get_log_level_name(
        _In_ sai_log_level_t value);
extern const char* sai_metadata_get_meter_type_name(
        _In_ sai_meter_type_t value);
extern const char* sai_metadata_get_mirror_session_type_name(
        _In_ sai_mirror_session_type_t value);
extern const char* sai_metadata_get_native_hash_field_name(
        _In_ sai_native_hash_field_t value);
extern const char* sai_metadata_get_next_hop_group_type_name(
        _In_ sai_next_hop_group_type_t value);
extern const char* sai_metadata_get_next_hop_type_name(
        _In_ sai_next_hop_type_t value);
extern const char* sai_metadata_get_object_type_name(
        _In_ sai_object_type_t value);
extern const char* sai_metadata_get_packet_action_name(
        _In_ sai_packet_action_t value);
extern const char* sai_metadata_get_packet_color_name(
        _In_ sai_packet_color_t value);
extern const char* sai_metadata_get_packet_vlan_name(
        _In_ sai_packet_vlan_t value);
extern const char* sai_metadata_get_policer_color_source_name(
        _In_ sai_policer_color_source_t value);
extern const char* sai_metadata_get_policer_mode_name(
        _In_ sai_policer_mode_t value);
extern const char* sai_metadata_get_policer_stat_name(
        _In_ sai_policer_stat_t value);
extern const char* sai_metadata_get_port_bind_mode_name(
        _In_ sai_port_bind_mode_t value);
extern const char* sai_metadata_get_port_breakout_mode_type_name(
        _In_ sai_port_breakout_mode_type_t value);
extern const char* sai_metadata_get_port_fec_mode_name(
        _In_ sai_port_fec_mode_t value);
extern const char* sai_metadata_get_port_flow_control_mode_name(
        _In_ sai_port_flow_control_mode_t value);
extern const char* sai_metadata_get_port_internal_loopback_mode_name(
        _In_ sai_port_internal_loopback_mode_t value);
extern const char* sai_metadata_get_port_media_type_name(
        _In_ sai_port_media_type_t value);
extern const char* sai_metadata_get_port_oper_status_name(
        _In_ sai_port_oper_status_t value);
extern const char* sai_metadata_get_port_stat_name(
        _In_ sai_port_stat_t value);
extern const char* sai_metadata_get_port_type_name(
        _In_ sai_port_type_t value);
extern const char* sai_metadata_get_qos_map_type_name(
        _In_ sai_qos_map_type_t value);
extern const char* sai_metadata_get_queue_pfc_deadlock_event_type_name(
        _In_ sai_queue_pfc_deadlock_event_type_t value);
extern const char* sai_metadata_get_queue_stat_name(
        _In_ sai_queue_stat_t value);
extern const char* sai_metadata_get_queue_type_name(
        _In_ sai_queue_type_t value);
extern const char* sai_metadata_get_router_interface_type_name(
        _In_ sai_router_interface_type_t value);
extern const char* sai_metadata_get_samplepacket_mode_name(
        _In_ sai_samplepacket_mode_t value);
extern const char* sai_metadata_get_samplepacket_type_name(
        _In_ sai_samplepacket_type_t value);
extern const char* sai_metadata_get_scheduling_type_name(
        _In_ sai_scheduling_type_t value);
extern const char* sai_metadata_get_status_name(
        _In_ sai_status_t value);
extern const char* sai_metadata_get_stp_port_state_name(
        _In_ sai_stp_port_state_t value);
extern const char* sai_metadata_get_switch_mcast_snooping_capability_name(
        _In_ sai_switch_mcast_snooping_capability_t value);
extern const char* sai_metadata_get_switch_oper_status_name(
        _In_ sai_switch_oper_status_t value);
extern const char* sai_metadata_get_switch_restart_type_name(
        _In_ sai_switch_restart_type_t value);
extern const char* sai_metadata_get_switch_switching_mode_name(
        _In_ sai_switch_switching_mode_t value);
extern const char* sai_metadata_get_tunnel_decap_ecn_mode_name(
        _In_ sai_tunnel_decap_ecn_mode_t value);
extern const char* sai_metadata_get_tunnel_dscp_mode_name(
        _In_ sai_tunnel_dscp_mode_t value);
extern const char* sai_metadata_get_tunnel_encap_ecn_mode_name(
        _In_ sai_tunnel_encap_ecn_mode_t value);
extern const char* sai_metadata_get_tunnel_map_type_name(
        _In_ sai_tunnel_map_type_t value);
extern const char* sai_metadata_get_tunnel_term_table_entry_type_name(
        _In_ sai_tunnel_term_table_entry_type_t value);
extern const char* sai_metadata_get_tunnel_ttl_mode_name(
        _In_ sai_tunnel_ttl_mode_t value);
extern const char* sai_metadata_get_tunnel_type_name(
        _In_ sai_tunnel_type_t value);
extern const char* sai_metadata_get_udf_base_name(
        _In_ sai_udf_base_t value);
extern const char* sai_metadata_get_udf_group_type_name(
        _In_ sai_udf_group_type_t value);
extern const char* sai_metadata_get_vlan_mcast_lookup_key_type_name(
        _In_ sai_vlan_mcast_lookup_key_type_t value);
extern const char* sai_metadata_get_vlan_stat_name(
        _In_ sai_vlan_stat_t value);
extern const char* sai_metadata_get_vlan_tagging_mode_name(
        _In_ sai_vlan_tagging_mode_t value);
extern sai_acl_api_t *sai_metadata_sai_acl_api;
extern sai_bridge_api_t *sai_metadata_sai_bridge_api;
extern sai_buffer_api_t *sai_metadata_sai_buffer_api;
extern sai_fdb_api_t *sai_metadata_sai_fdb_api;
extern sai_hash_api_t *sai_metadata_sai_hash_api;
extern sai_hostif_api_t *sai_metadata_sai_hostif_api;
extern sai_ipmc_api_t *sai_metadata_sai_ipmc_api;
extern sai_ipmc_group_api_t *sai_metadata_sai_ipmc_group_api;
extern sai_l2mc_api_t *sai_metadata_sai_l2mc_api;
extern sai_l2mc_group_api_t *sai_metadata_sai_l2mc_group_api;
extern sai_lag_api_t *sai_metadata_sai_lag_api;
extern sai_mcast_fdb_api_t *sai_metadata_sai_mcast_fdb_api;
extern sai_mirror_api_t *sai_metadata_sai_mirror_api;
extern sai_neighbor_api_t *sai_metadata_sai_neighbor_api;
extern sai_next_hop_api_t *sai_metadata_sai_next_hop_api;
extern sai_next_hop_group_api_t *sai_metadata_sai_next_hop_group_api;
extern sai_policer_api_t *sai_metadata_sai_policer_api;
extern sai_port_api_t *sai_metadata_sai_port_api;
extern sai_qos_map_api_t *sai_metadata_sai_qos_map_api;
extern sai_queue_api_t *sai_metadata_sai_queue_api;
extern sai_route_api_t *sai_metadata_sai_route_api;
extern sai_router_interface_api_t *sai_metadata_sai_router_interface_api;
extern sai_rpf_group_api_t *sai_metadata_sai_rpf_group_api;
extern sai_samplepacket_api_t *sai_metadata_sai_samplepacket_api;
extern sai_scheduler_api_t *sai_metadata_sai_scheduler_api;
extern sai_scheduler_group_api_t *sai_metadata_sai_scheduler_group_api;
extern sai_stp_api_t *sai_metadata_sai_stp_api;
extern sai_switch_api_t *sai_metadata_sai_switch_api;
extern sai_tunnel_api_t *sai_metadata_sai_tunnel_api;
extern sai_udf_api_t *sai_metadata_sai_udf_api;
extern sai_virtual_router_api_t *sai_metadata_sai_virtual_router_api;
extern sai_vlan_api_t *sai_metadata_sai_vlan_api;
extern sai_wred_api_t *sai_metadata_sai_wred_api;
typedef sai_status_t (*sai_api_query_fn)(
        _In_ sai_api_t sai_api_id,
        _Out_ void** api_method_table);
extern int sai_metadata_apis_query(
    _In_ const sai_api_query_fn api_query);
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_PORT;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_LAG;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_VIRTUAL_ROUTER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_NEXT_HOP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_NEXT_HOP_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_ROUTER_INTERFACE;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_ACL_TABLE;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_ACL_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_ACL_COUNTER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_ACL_RANGE;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_ACL_TABLE_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_ACL_TABLE_GROUP_MEMBER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_HOSTIF;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_MIRROR_SESSION;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_SAMPLEPACKET;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_STP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_HOSTIF_TRAP_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_POLICER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_WRED;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_QOS_MAP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_QUEUE;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_SCHEDULER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_SCHEDULER_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_BUFFER_POOL;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_BUFFER_PROFILE;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_INGRESS_PRIORITY_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_LAG_MEMBER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_HASH;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_UDF;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_UDF_MATCH;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_UDF_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_FDB_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_SWITCH;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_HOSTIF_TRAP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_HOSTIF_TABLE_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_NEIGHBOR_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_ROUTE_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_VLAN;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_VLAN_MEMBER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_HOSTIF_PACKET;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_TUNNEL_MAP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_TUNNEL;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_TUNNEL_TERM_TABLE_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_FDB_FLUSH;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_NEXT_HOP_GROUP_MEMBER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_STP_PORT;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_RPF_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_RPF_GROUP_MEMBER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_L2MC_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_L2MC_GROUP_MEMBER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_IPMC_GROUP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_IPMC_GROUP_MEMBER;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_L2MC_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_IPMC_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_MCAST_FDB_ENTRY;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_HOSTIF_USER_DEFINED_TRAP;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_BRIDGE;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_BRIDGE_PORT;
extern const sai_object_type_info_t sai_metadata_object_type_info_SAI_OBJECT_TYPE_TUNNEL_MAP_ENTRY;
extern const sai_object_type_info_t* sai_metadata_all_object_type_infos[];
extern const sai_attr_metadata_t* sai_metadata_attr_sorted_by_id_name[];
extern const size_t sai_metadata_attr_sorted_by_id_name_count;
#endif /* __SAI_METADATA_H__ */
